language: python
python:
  - "2.7"
  - "3.4"
before_install:
  # We need GraphViz
  - "sudo apt-get install graphviz 2>&1 | tail -n 2"
install:
  - pip install nose
  - pip install doctest-ignore-unicode
  - pip install coveralls
  - python setup.py develop
script:
  - coverage run --source=pygraphviz nosetests
after_success:
  - coveralls