language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
addons:
  apt:
    packages:
      - graphviz
matrix:
  include:
    - os: linux
      python: 3.7
      dist: xenial
      sudo: true
    - os: osx
      language: generic
      before_install: brew install graphviz
  allow_failures:
    - os: osx
install:
  - pip install mock nose doctest-ignore-unicode coveralls
  - python setup.py develop
script:
  - nosetests --with-coverage --cover-package=pygraphviz
  - python setup.py bdist_wheel
after_success:
  - coveralls
