language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6-dev"
  - "pypy"
addons:
  apt:
    packages:
      - graphviz
matrix:
  include:
    - os: osx
      language: generic
      before_install: brew install graphviz
  allow_failures:
    - os: osx
install:
  - pip install mock
  - pip install nose
  - pip install doctest-ignore-unicode
  - pip install coveralls
  - python setup.py develop
script:
  - nosetests --with-coverage --cover-package=pygraphviz
  - python setup.py bdist_wheel
after_success:
  - coveralls
